### ISSUE TITLE
Error happens when chaning output_size

### ISSUE THREAD

**Issue by YinghaoHuang91** [tranluan/Nonlinear_Face_3DMM#3]
Hi Luan, I played around with the code you released. And I found when I changed the output_size from 224, the default one, to 512, and run the program **_rendering_example.py_**, it constantly throws this error:

    InvalidArgumentError: Incompatible shapes: [262144] vs. [50176]
    
The error seems from line 157 of _**rendering_ops.file**_. Can you please help have a look? Thanks!

**Comment by tranluan** [comment]
Have you edit the zbuffer rendering cuda code and recompile. Currently, the image size is hardcoded.
In lasted commit:
cuda_op_kernel_v2_sz224.cc (line41)
cuda_op_kernel_v2_sz224.cu.cc (line137)

**Comment by YinghaoHuang91** [comment]
Yeah, I see. I tried it, it works! Thanks!

**Comment by huxianer** [comment]
@YinghaoHuang91 @tranluan Hi,I can`t find the test code,Could you give any help?Thanks!

**Comment by YinghaoHuang91** [comment]
Hi if I remembered correctly, the code I tested is this one: 
`https://github.com/tranluan/Nonlinear_Face_3DMM/blob/master/rendering_example.py. `
Still you might want to follow the latest instruction since the code structure has changed a lot.

**Comment by huxianer** [comment]
@YinghaoHuang91 Thank you!But the script use the given sample_data.npz.Here,I want to use the model I have trained.

**Comment by tranluan** [comment]
> @YinghaoHuang91 @tranluan Hi,I can`t find the test code,Could you give any help?Thanks!

@huxianer Could you please elaborate on what do you need?

**Comment by huxianer** [comment]
@tranluan Hi，thank you for your wonderful job.Here,I have trained my own model,but I can`t find the test code.How to use the trained model?I try to complete the test code,but something wrong meet with.So,if you share the test code,which is grateful to me.Thank you

**Comment by MagicJackStone** [comment]
@YinghaoHuang91 Hi，do you change the resolution successfully？ Tks.
