### ISSUE TITLE
TensorFlow 2.0

### ISSUE THREAD

**Issue by Adriana618-Love** [tranluan/Nonlinear_Face_3DMM#40]
Excuse me, first of all congratulate him on his work which is really interesting. The problem I have is because I want to run the code but when analyzing the ".sh" that you provide, you used TF 1.8. Is there a way to compile it with TF 2.0 ?, some modification or maybe do the compilation "manually"

**Comment by huyanfei-cqupt** [comment]
> 
> 
> Excuse me, first of all congratulate him on his work which is really interesting. The problem I have is because I want to run the code but when analyzing the ".sh" that you provide, you used TF 1.8. Is there a way to compile it with TF 2.0 ?, some modification or maybe do the compilation "manually"

hi，what's mean this below functions？ thanks
` def m2full(self, m):
        return m * self.std_m_tf + self.mean_m_tf

    def shape2full(self, shape):
        return shape * self.std_shape_tf + self.mean_shape_tf`

**Comment by tranluan** [comment]
Please see this link
https://www.tensorflow.org/guide/create_op
