### ISSUE TITLE
NotFoundError: ./TF_newop/cuda_op_kernel_v2_sz224.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by huyanfei-cqupt** [tranluan/Nonlinear_Face_3DMM#41]
Hello,

I tried to train the model. However I got a few issues. @tranluan can you help me to resolve this? Thanks in advance.

**Comment by Nancyhhh** [comment]
I have the same problem with you , if you have solved it , please share with me, it  is so nice of you,have a nice day !

**Comment by huyanfei-cqupt** [comment]
Hi,
I added the environment variables of gcc again, and it succeeded after restarting the computer.
