### ISSUE TITLE
./compile_op_v2_sz224.sh: 行 15: nvcc: 未找到命令 g++: error: cuda_op_kernel_v2_sz224.cu.o: 没有那个文件或目录

### ISSUE THREAD

**Issue by huyanfei-cqupt** [tranluan/Nonlinear_Face_3DMM#42]
I got the above error When i was compiling.  Can anyone help me?

**Comment by Nancyhhh** [comment]
hi, could you tell me how you solved this problem? thank you very much !

**Comment by anewusername77** [comment]
> > I got the above error When i was compiling. Can anyone help me?
> > the error was resolved.
> > you must reset the nvcc's environment PATH

请问你怎么解决的这个问题？加什么版本gcc的环境变量？

**Comment by huyanfei-cqupt** [comment]
您的来信来信已收到，谢谢。
