### ISSUE TITLE
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'ZbufferTriV2Sz224' with these attrs.  Registered devices: [CPU], Registered kernels:   device='GPU'       [[Node: ZbufferTriV2Sz224_15 = ZbufferTriV2Sz224[](transpose_16, Const_3, Squeeze_31)]]'

### ISSUE THREAD

**Issue by huyanfei-cqupt** [tranluan/Nonlinear_Face_3DMM#46]
@tranluan when I try to switch the L loss, but I encounter the error.

**Comment by tranluan** [comment]
Are you using CPU?

**Comment by huyanfei-cqupt** [comment]
@tranluan I use one GPU to run the code

**Comment by huyanfei-cqupt** [comment]
I haven't changed the source code anywhere.After the pre-training, I changed the parameters directly on the command line, and then this problem occurred.
The pre-training is good, and this problem has never occurred.
