### ISSUE TITLE
Missing perceptual loss (G_loss_frecon = tf.zeros(1))

### ISSUE THREAD

**Issue by HOMGH** [tranluan/Nonlinear_Face_3DMM#49]
Hi,
It seems that perceptual loss has not been calculated in the code. Right? Would you please share that missing part of the code.
Thanks.

**Comment by huyanfei-cqupt** [comment]
> 
> 
> Hi,
> It seems that perceptual loss has not been calculated in the code. Right? Would you please share that missing part of the code.
> Thanks.

me too，I also find this pronlem.

**Comment by huyanfei-cqupt** [comment]
@HOMGH hi，Is it convenient to share your email address? It will be much more convenient for us to discuss related issues.

**Comment by tranluan** [comment]
Answered in #48

**Comment by HOMGH** [comment]
> @HOMGH hi，Is it convenient to share your email address? It will be much more convenient for us to discuss related issues.

yes. Please send your email address, I will contact you.

**Comment by huyanfei-cqupt** [comment]
> > @HOMGH hi，Is it convenient to share your email address? It will be much more convenient for us to discuss related issues.
> 
> yes. Please send your email address, I will contact you.

Sorry, @HOMGH Please forgive me for seeing your reply.  my email is "s180131232@stu.cqupt.edu.cn", my name is Huyanfei. Thank you very much!
