### ISSUE TITLE
No implementation details are found for GCGAN decoder and encoder.

### ISSUE THREAD

**Issue by HaiyongJiang** [tranluan/Nonlinear_Face_3DMM#6]
Hi @tranluan, your paper looks very interesting, and I want to try the released source code. But I found that the implementation of the decoder and encoder function was left empty, e.g. GCGAN.generator_encoder and GCGAN.generator_decoder_shape. Could you help resolve this?

**Comment by CHELSEA234** [comment]
I had same issues...
